'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(d){var h=function(){};h.prototype=d;return new h};$jscomp.underscoreProtoCanBeSet=function(){var d={a:!0},h={};try{return h.__proto__=d,h.a}catch(g){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(d,h){d.__proto__=h;if(d.__proto__!==h)throw new TypeError(d+" is not extensible");return d}:null;
$jscomp.inherits=function(d,h){d.prototype=$jscomp.objectCreate(h.prototype);d.prototype.constructor=d;if($jscomp.setPrototypeOf){var g=$jscomp.setPrototypeOf;g(d,h)}else for(g in h)if("prototype"!=g)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(h,g);e&&Object.defineProperty(d,g,e)}else d[g]=h[g];d.superClass_=h.prototype};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,h,g){d!=Array.prototype&&d!=Object.prototype&&(d[h]=g.value)};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var d=0;return function(h){return $jscomp.SYMBOL_PREFIX+(h||"")+d++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(d){var h=0;return $jscomp.iteratorPrototype(function(){return h<d.length?{done:!1,value:d[h++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.iteratorFromArray=function(d,h){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var g=0,e={next:function(){if(g<d.length){var l=g++;return{value:h(l,d[l]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(d,h,g,e){if(h){g=$jscomp.global;d=d.split(".");for(e=0;e<d.length-1;e++){var l=d[e];l in g||(g[l]={});g=g[l]}d=d[d.length-1];e=g[d];h=h(e);h!=e&&null!=h&&$jscomp.defineProperty(g,d,{configurable:!0,writable:!0,value:h})}};$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(d){return d?d:function(d,g,e){var h=this.length||0;0>g&&(g=Math.max(0,h+g));if(null==e||e>h)e=h;e=Number(e);0>e&&(e=Math.max(0,h+e));for(g=Number(g||0);g<e;g++)this[g]=d;return this}},"es6","es3");$jscomp.polyfill("Number.isNaN",function(d){return d?d:function(d){return"number"===typeof d&&isNaN(d)}},"es6","es3");$jscomp.makeIterator=function(d){$jscomp.initSymbolIterator();var h=d[Symbol.iterator];return h?h.call(d):$jscomp.arrayIterator(d)};
$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(d){function h(){this.batch_=null}function g(d){return d instanceof l?d:new l(function(e,g){e(d)})}if(d&&!$jscomp.FORCE_POLYFILL_PROMISE)return d;h.prototype.asyncExecute=function(d){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(d);return this};h.prototype.asyncExecuteBatch_=function(){var d=this;this.asyncExecuteFunction(function(){d.executeBatch_()})};var e=$jscomp.global.setTimeout;h.prototype.asyncExecuteFunction=function(d){e(d,
0)};h.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var e=0;e<d.length;++e){var g=d[e];delete d[e];try{g()}catch(n){this.asyncThrow_(n)}}}this.batch_=null};h.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var l=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var e=this.createResolveAndReject_();try{d(e.resolve,e.reject)}catch(q){e.reject(q)}};l.prototype.createResolveAndReject_=
function(){function d(d){return function(h){g||(g=!0,d.call(e,h))}}var e=this,g=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};l.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof l)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var e=null!=d;break a;case "function":e=!0;break a;default:e=!1}e?this.resolveToNonPromiseObj_(d):this.fulfill_(d)}};l.prototype.resolveToNonPromiseObj_=function(d){var e=
void 0;try{e=d.then}catch(q){this.reject_(q);return}"function"==typeof e?this.settleSameAsThenable_(e,d):this.fulfill_(d)};l.prototype.reject_=function(d){this.settle_(2,d)};l.prototype.fulfill_=function(d){this.settle_(1,d)};l.prototype.settle_=function(d,e){if(0!=this.state_)throw Error("Cannot settle("+d+", "+e|"): Promise already settled in state"+this.state_);this.state_=d;this.result_=e;this.executeOnSettledCallbacks_()};l.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=
this.onSettledCallbacks_,e=0;e<d.length;++e)d[e].call(),d[e]=null;this.onSettledCallbacks_=null}};var v=new h;l.prototype.settleSameAsPromise_=function(d){var e=this.createResolveAndReject_();d.callWhenSettled_(e.resolve,e.reject)};l.prototype.settleSameAsThenable_=function(d,e){var g=this.createResolveAndReject_();try{d.call(e,g.resolve,g.reject)}catch(n){g.reject(n)}};l.prototype.then=function(d,e){function g(d,e){return"function"==typeof d?function(e){try{h(d(e))}catch(F){k(F)}}:e}var h,k,m=new l(function(d,
e){h=d;k=e});this.callWhenSettled_(g(d,h),g(e,k));return m};l.prototype.catch=function(d){return this.then(void 0,d)};l.prototype.callWhenSettled_=function(d,e){function g(){switch(h.state_){case 1:d(h.result_);break;case 2:e(h.result_);break;default:throw Error("Unexpected state: "+h.state_);}}var h=this;null==this.onSettledCallbacks_?v.asyncExecute(g):this.onSettledCallbacks_.push(function(){v.asyncExecute(g)})};l.resolve=g;l.reject=function(d){return new l(function(e,g){g(d)})};l.race=function(d){return new l(function(e,
h){for(var l=$jscomp.makeIterator(d),k=l.next();!k.done;k=l.next())g(k.value).callWhenSettled_(e,h)})};l.all=function(d){var e=$jscomp.makeIterator(d),h=e.next();return h.done?g([]):new l(function(d,l){function m(e){return function(g){k[e]=g;n--;0==n&&d(k)}}var k=[],n=0;do k.push(void 0),n++,g(h.value).callWhenSettled_(m(k.length-1),l),h=e.next();while(!h.done)})};return l},"es6","es3");$jscomp.owns=function(d,h){return Object.prototype.hasOwnProperty.call(d,h)};
$jscomp.polyfill("Object.assign",function(d){return d?d:function(d,g){for(var e=1;e<arguments.length;e++){var h=arguments[e];if(h)for(var v in h)$jscomp.owns(h,v)&&(d[v]=h[v])}return d}},"es6","es3");
(function(d,h){"object"===typeof exports&&"undefined"!==typeof module?module.exports=h():"function"===typeof define&&define.amd?define(h):d.Unitary=h()})(this,function(){function d(a){var b=a.target.getBoundingClientRect(),c=this.X(a.clientX-b.left);b=this.Y(a.clientY-b.top);c=new x.Point(c,b);var f=!1;a.stopPropagation=function(){f=!0};for(b=this.objects.length-1;0<=b&&!f;b=0|b-1)this.objects[b].has&&this.objects[b].has(c)&&this.objects[b].trigger(a.type,a)}function h(a){this.canvas.beginPath();
this.canvas.moveTo(this.X(a.points[0].x),this.Y(a.points[0].y));for(var b=0,c=a.points.length;b<c;b=0|b+1)this.canvas.lineTo(this.X(a.points[b].x),this.Y(a.points[b].y));this.canvas.closePath();null!==a.style.fillStyle&&this.canvas.fill();this.canvas.stroke()}var g=function(){this.style={fillStyle:null,strokeStyle:null}};g.prototype.equals=function(a){return this.name()===a.name()};g.prototype.setFillColor=function(a){this.style.fillStyle=a;return this};g.prototype.setFillStyle=function(a){this.style.fillStyle=
a;return this};g.prototype.setStrokeColor=function(a){this.style.strokeStyle=a;return this};g.prototype.setStrokeStyle=function(a){this.style.strokeStyle=a;return this};g.prototype.setStyle=function(a){for(var b=Object.keys(a),c=0,f=b.length;c<f;c++)this.style[b[c]]=a[b[c]];return this};g.prototype.move=function(a,b){return this};g.prototype.moveX=function(a){return this.move(a,0)};g.prototype.moveY=function(a){return this.move(0,a)};g.prototype.has=function(a){return!1};g.prototype.name=function(){return"UnitaryObject"};
var e=function(){var a=g.call(this)||this;a.lineDash=null;a.lineCap=null;a.lineDashOffset=null;a.lineJoin=null;a.lineWidth=null;return a};$jscomp.inherits(e,g);e.prototype.getLineDash=function(){return this.lineDash};e.prototype.setLineDash=function(a){this.lineDash=a;return this};e.prototype.getLineCap=function(){return this.lineCap};e.prototype.setLineCap=function(a){this.lineCap=a;return this};e.prototype.getLineDashOffset=function(){return this.lineDashOffset};e.prototype.setLineDashOffset=function(a){this.lineDashOffset=
a;return this};e.prototype.getLineJoin=function(){return this.lineJoin};e.prototype.setLineJoin=function(a){this.lineJoin=a;return this};e.prototype.getLineWidth=function(){return this.lineWidth};e.prototype.setLineWidth=function(a){this.lineWidth=a;return this};e.prototype.name=function(){return"ContouredObject"};var l=function(a){var b,c=[];for(b=0;b<arguments.length;++b)c[b-0]=arguments[b];b=e.call(this)||this;Array.isArray(c[0])?b.controlPoints=c[0]:b.controlPoints=c;if(4<b.controlPoints.length){for(var f=
c=0,d=b.controlPoints.length-1;f<d;f++){var O=b.controlPoints[f+1].x-b.controlPoints[f].x,g=b.controlPoints[f+1].y-b.controlPoints[f].y;c+=Math.sqrt(O*O+g*g)}b.step=1/c}return b};$jscomp.inherits(l,e);l.prototype.setStep=function(a){this.step=a;return this};l.prototype.move=function(a,b){if(0===a&&0===b)return this;for(var c=this.controlPoints.concat(),f=0,d=c.length;f<d;f=0|f+1)c[f]=c[f].move(a,b);return(new l(c)).setStep(this.step)};l.prototype.name=function(){return"BezierCurve"};var v=function(a){return 0<
a?a:-a},N=function(a){return(0|a)===a},K=function(a,b){return a<b?K(b,a):0>a?K(-a,b):0>b?K(a,-b):0===b?a:K(b,a%b)},q=function(a,b){return(0|1E6*a)/1E6===(0|1E6*b)/1E6},n=function(a,b){var c=g.call(this)||this;c.x=a;c.y=b;return c};$jscomp.inherits(n,g);n.prototype.moveTo=function(a,b){return this.x===a&&this.y===b?this:(new n(a,b)).setStyle(this.style)};n.prototype.move=function(a,b){return 0===a&&0===b?this:(new n(this.x+a,this.y+b)).setStyle(this.style)};n.prototype.rotate=function(a,b){return 0===
a%(2*Math.PI)?this:(new n(Math.cos(a)*(this.x-b.x)-Math.sin(a)*(this.y-b.y)+b.x,Math.sin(a)*(this.x-b.x)+Math.cos(a)*(this.y-b.y)+b.y)).setStyle(this.style)};n.prototype.toString=function(){return"("+this.x+", "+this.y+")"};n.prototype.inspect=function(){return"("+this.x+", "+this.y+")"};n.prototype.equals=function(a){return g.prototype.equals.call(this,a)?q(this.x,a.x)&&q(this.y,a.y):!1};n.prototype.toVector=function(){return new m(this.x,this.y)};n.fromPolar=function(a,b){return new n(a*Math.cos(b),
a*Math.sin(b))};n.prototype.name=function(){return"Point"};var k=function(a){var b,c=[];for(b=0;b<arguments.length;++b)c[b-0]=arguments[b];b=g.call(this)||this;if(1===c.length&&Array.isArray(c[0])){b.component=Array(c[0].length);for(var f=0,d=c[0].length;f<d;f=0|f+1)b.component[f]=c[0][f]}else for(b.component=Array(c.length),f=0,d=c.length;f<d;f=0|f+1)b.component[f]=c[f];return b};$jscomp.inherits(k,g);k.prototype.add=function(a){if(this.component.length!==a.component.length)throw Error("dimention of each vector are different.");
for(var b=Array(this.component.length),c=0,f=this.component.length;c<f;c=0|c+1)b[c]=this.component[c]+a.component[c];return new k(b)};k.prototype.subtract=function(a){return this.add(a.multiple(-1))};k.prototype.product=function(a){if(this.component.length!==a.component.length)throw Error("dimention of each vector are different.");for(var b=0,c=0,f=this.component.length;c<f;c=0|c+1)b+=this.component[c]*a.component[c];return b};k.prototype.multiple=function(a){if(1===a)return this;for(var b=Array(this.component.length),
c=0,f=this.component.length;c<f;c=0|c+1)b[c]=a*this.component[c];return new k(b)};k.prototype.abs=function(){for(var a=0,b=0,c=this.component.length;b<c;b=0|b+1)a+=this.component[b]*this.component[b];return Math.sqrt(a)};k.prototype.normalize=function(){return this.multiple(1/this.abs())};k.prototype.equals=function(a){if(this.component.length!==a.component.length)return!1;for(var b=0,c=this.component.length;b<c;b=0|b+1)if(this.component[b]!==a.component[b])return!1;return!0};k.prototype.move=function(a){for(var b=
[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];return this.add(new k(b))};k.prototype.name=function(){return"BaseVector"};var m=function(a){var b,c=[];for(b=0;b<arguments.length;++b)c[b-0]=arguments[b];if(2===c.length)b=k.call(this,c[0],c[1])||this,b.x=c[0],b.y=c[1];else if(1===c.length)b=k.call(this,c[0].x,c[0].y)||this,b.x=c[0].x,b.y=c[0].y;else throw Error("unexpected arguments was given.");b.r=Math.sqrt(b.x*b.x+b.y*b.y);b.theta=(Math.atan2(b.y,b.x)+2*Math.PI)%(2*Math.PI);return b};$jscomp.inherits(m,
k);m.prototype.add=function(a){a=k.prototype.add.call(this,a);return new m(a.component[0],a.component[1])};m.prototype.subtract=function(a){a=k.prototype.subtract.call(this,a);return new m(a.component[0],a.component[1])};m.prototype.multiple=function(a){a=k.prototype.multiple.call(this,a);return new m(a.component[0],a.component[1])};m.prototype.abs=function(){return this.r};m.prototype.equals=function(a){return k.prototype.equals.call(this,a)?q(this.x,a.x)&&q(this.y,a.y):!1};m.prototype.toPoint=function(){return new n(this.x,
this.y)};m.prototype.move=function(a,b){return 0===a&&0===b?this:new m(this.x+a,this.y+b)};m.prototype.name=function(){return"Vector"};var B=function(a){var b,c=[];for(b=0;b<arguments.length;++b)c[b-0]=arguments[b];if(3===c.length)b=k.call(this,c[0],c[1],c[2])||this,b.x=c[0],b.y=c[1],b.z=c[2];else if(1===c.length)b=k.call(this,c[0].x,c[0].y,c[0].z)||this,b.x=c[0].x,b.y=c[0].y,b.z=c[0].z;else throw Error("unexpected arguments was given.");return b};$jscomp.inherits(B,k);B.prototype.add=function(a){a=
k.prototype.add.call(this,a);return new B(a.component[0],a.component[1],a.component[2])};B.prototype.subtract=function(a){a=k.prototype.subtract.call(this,a);return new B(a.component[0],a.component[1],a.component[2])};B.prototype.multiple=function(a){a=k.prototype.multiple.call(this,a);return new B(a.component[0],a.component[1],a.component[2])};B.prototype.move=function(a,b,c){return 0===a&&0===b&&0===c?this:new B(this.x+a,this.y+b,this.z+c)};B.prototype.name=function(){return"Vector3D"};var w=function(a,
b){var c=e.call(this)||this;c.center=a;c.r=b;c.anticlockwise=!1;return c};$jscomp.inherits(w,e);w.prototype.clone=function(){for(var a=(new w(this.center,this.r)).setStyle(this.style),b=Object.keys(this),c=0,f=b.length;c<f;c++)"style"!==b[c]&&(a[b[c]]=this[b[c]]);return a};w.prototype.moveTo=function(a,b){if(this.center.x===a&&this.center.y===b)return this;var c=this.clone();c.center=this.center.moveTo(a,b);return c};w.prototype.move=function(a,b){if(0===a&&0===b)return this;var c=this.clone();c.center=
this.center.move(a,b);return c};w.prototype.getEquation=function(){return"(x"+(0===this.center.x?"":(0<=-this.center.x?"+":"-")+v(this.center.x))+")^2+(y"+(0===this.center.y?"":(0<=-this.center.y?"+":"-")+v(this.center.y))+")^2="+this.r+"^2"};w.prototype.equals=function(a){return e.prototype.equals.call(this,a)?this.center.equals(a.center)&&q(this.r,a.r):!1};w.prototype.has=function(a){return(new m(a)).subtract(new m(this.center)).abs()<=this.r};w.prototype.setAnticlockwise=function(a){if(this.anticlockwise===
a)return this;var b=this.clone();b.anticlockwise=a;return b};w.prototype.name=function(){return"Circle"};$jscomp.global.Object.defineProperties(w.prototype,{Origin:{configurable:!0,enumerable:!0,get:function(){return this.center}},radius:{configurable:!0,enumerable:!0,get:function(){return this.r}}});var z=function(a,b,c,f){f=void 0===f?0:f;var d=e.call(this)||this;d.center=a;d.r=b;d.endAngle=c;d.startAngle=f;d.anticlockwise=!1;return d};$jscomp.inherits(z,e);z.prototype.clone=function(){for(var a=
(new z(this.center,this.r,this.endAngle,this.startAngle)).setStyle(this.style),b=Object.keys(this),c=0,f=b.length;c<f;c++)"style"!==b[c]&&(a[b[c]]=this[b[c]]);return a};z.prototype.moveTo=function(a,b){if(this.center.x===a&&this.center.y===b)return this;var c=this.clone();c.center=this.center.moveTo(a,b);return c};z.prototype.move=function(a,b){if(0===a&&0===b)return this;var c=this.clone();c.center=this.center.move(a,b);return c};z.prototype.rotate=function(a){if(0===a%(2*Math.PI))return this;var b=
this.clone();b.endAngle+=a;b.startAngle+=a;return b};z.prototype.equals=function(a){return e.prototype.equals.call(this,a)?this.center.equals(a.center)&&q(this.r,a.r)&&0===(this.startAngle-a.startAngle)%(2*Math.PI)&&0===(this.endAngle-a.endAngle)%(2*Math.PI):!1};z.prototype.has=function(a){var b=Math.atan2(a.y,a.x);return(new m(a)).subtract(new m(this.center)).abs()<=this.r&&this.startAngle<=b&&b<=this.endAngle};z.prototype.setAnticlockwise=function(a){if(this.anticlockwise===a)return this;var b=
this.clone();b.anticlockwise=a;return b};z.prototype.name=function(){return"CircularSector"};$jscomp.global.Object.defineProperties(z.prototype,{Origin:{configurable:!0,enumerable:!0,get:function(){return this.center}},radius:{configurable:!0,enumerable:!0,get:function(){return this.r}}});var F=function(a,b,c){c=void 0===c?30:c;var f=e.call(this)||this;f.x=a;f.y=b;f.scale=c;f.start=0;f.end=2*Math.PI;return f};$jscomp.inherits(F,e);F.prototype.setRange=function(a,b){this.start=a;this.end=b;return this};
F.prototype.equals=function(){return!1};F.prototype.moveX=function(){};F.prototype.moveY=function(){};F.prototype.name=function(){return"Curve"};var C=function(a,b,c){var f=e.call(this)||this;f.center=a;f.Origin=a;f.innerRadius=b;f.outerRadius=c;return f};$jscomp.inherits(C,e);C.prototype.moveTo=function(a,b){return this.center.x===a&&this.center.y===b?this:(new C(this.center.moveTo(a,b),this.innerRadius,this.outerRadius)).setStyle(this.style)};C.prototype.move=function(a,b){return 0===a&&0===b?this:
(new C(this.center.move(a,b),this.innerRadius,this.outerRadius)).setStyle(this.style)};C.prototype.equals=function(a){return e.prototype.equals.call(this,a)?this.center.equals(a.center)&&q(this.innerRadius,a.innerRadius)&&q(this.outerRadius,a.outerRadius):!1};C.prototype.has=function(a){a=(new m(a)).subtract(new m(this.center)).abs();return(this.innerRadius<a||q(this.innerRadius,a))&&(a<this.outerRadius||q(a,this.outerRadius))};C.prototype.name=function(){return"Doughnut"};var A=function(a,b,c){var f=
e.call(this)||this;f.center=a;f.a=b;f.b=c;f.majorAxis=2*Math.max(b,c);f.minorAxis=2*Math.min(b,c);f.anticlockwise=!1;f.angle=0;return f};$jscomp.inherits(A,e);A.prototype.clone=function(){for(var a=(new A(this.center,this.a,this.b)).setStyle(this.style),b=Object.keys(this),c=0,f=b.length;c<f;c++)"style"!==b[c]&&(a[b[c]]=this[b[c]]);return a};A.prototype.moveTo=function(a,b){if(this.center.x===a&&this.center.y===b)return this;var c=this.clone();c.center=this.center.moveTo(a,b);return c};A.prototype.move=
function(a,b){if(0===a&&0===b)return this;var c=this.clone();c.center=this.center.move(a,b);return c};A.prototype.rotate=function(a){if(0===a%(2*Math.PI))return this;var b=this.clone();b.angle+=a;return b};A.prototype.equals=function(a){return e.prototype.equals.call(this,a)?this.center.equals(a.center)&&this.a===a.a&&this.b===a.b:!1};A.prototype.has=function(a){a=a.rotate(-this.angle,this.center);return 1>=Math.pow((a.x-this.center.x)/this.a,2)+Math.pow((a.y-this.center.y)/this.b,2)};A.prototype.setAnticlockwise=
function(a){if(this.anticlockwise===a)return this;var b=this.clone();b.anticlockwise=a;return b};A.prototype.name=function(){return"Ellipse"};$jscomp.global.Object.defineProperties(A.prototype,{Origin:{configurable:!0,enumerable:!0,get:function(){return this.center}}});var J=function(a,b){b=void 0===b?30:b;var c=e.call(this)||this;c.f=a;c.scale=b;c.start=null;c.end=null;return c};$jscomp.inherits(J,e);J.prototype.setRange=function(a,b){this.start=a;this.end=b;return this};J.prototype.equals=function(){return!1};
J.prototype.moveX=function(){};J.prototype.moveY=function(){};J.prototype.name=function(){return"Graph"};var G=function(a){var b,c=[];for(b=0;b<arguments.length;++b)c[b-0]=arguments[b];b=e.call(this)||this;Array.isArray(c[0])?b.group=c[0]:b.group=c;return b};$jscomp.inherits(G,e);G.prototype.has=function(a){for(var b=0,c=this.group.length;b<c;b++)if(this.group[b].has&&this.group[b].has(a))return!0;return!1};G.prototype.move=function(a,b){if(0===a&&0===b)return this;for(var c=this.group.concat(),f=
0,d=c.length;f<d;f=0|f+1)c[f].move&&(c[f]=c[f].move(a,b));return new G(c)};G.prototype.push=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];return new G(this.group.concat(b))};G.prototype.name=function(){return"Group"};var D=function(a,b){var c=g.call(this)||this;c.src=a;c.startPoint=b;c.dw=null;c.dh=null;c.sw=null;c.sh=null;c.sx=null;c.sy=null;return c};$jscomp.inherits(D,g);D.prototype.clone=function(){for(var a=(new D(this.src,this.startPoint)).setStyle(this.style),b=Object.keys(this),
c=0,f=b.length;c<f;c++)"style"!==b[c]&&(a[b[c]]=this[b[c]]);return a};D.prototype.trim=function(a,b,c,f,d){f=void 0===f?b:f;d=void 0===d?c:d;var e=this.clone();e.sx=a.x;e.sy=a.y;e.sw=b;e.sh=c;e.dw=f;e.dh=d;return e};D.prototype.resize=function(a,b){var c=this.clone();c.dw=a;c.dh=b;c.sw=this.sw;c.sh=this.sh;c.sx=this.sx;c.sy=this.sy;return c};D.prototype.equals=function(a){return g.prototype.equals.call(this,a)?this.src===a.src&&this.dx===a.dx&&this.dy===a.dy&&this.dw===a.dw&&this.dh===a.dh&&this.sw===
a.sw&&this.sh===a.sh&&this.sx===a.sx&&this.sy===a.sy:!1};D.prototype.move=function(a,b){if(0===a&&0===b)return this;var c=this.clone();c.startPoint=this.startPoint.move(a,b);return c};D.prototype.name=function(){return"Image"};$jscomp.global.Object.defineProperties(D.prototype,{dx:{configurable:!0,enumerable:!0,get:function(){return this.startPoint.x}},dy:{configurable:!0,enumerable:!0,get:function(){return this.startPoint.y}}});var r=function(a,b){if(a.equals(b))throw Error("A equals B. So AB couldn't construct line.");
var c=e.call(this)||this;c.points=[a,b];c.a=b.y-a.y;c.b=a.x-b.x;c.c=a.x*(a.y-b.y)-a.y*(a.x-b.x);N(c.a)&&N(c.b)&&N(c.c)&&(a=K(K(c.a,c.b),c.c),c.a/=a,c.b/=a,c.c/=a);0>c.a&&(c.a*=-1,c.b*=-1,c.c*=-1);0===c.a&&(c.c/=c.b,c.b=1);0===c.b&&(c.c/=c.a,c.a=1);return c};$jscomp.inherits(r,e);r.prototype.move=function(a,b){return 0===a&&0===b?this:(new r(this.points[0].move(a,b),this.points[1].move(a,b))).setStyle(this.style)};r.prototype.has=function(a){return q(this.a*a.x+this.b*a.y+this.c,0)};r.prototype.getEquation=
function(){var a=this.a,b=this.b,c=this.c,f="";0!==a&&(f+=(0<=a?"+":"-")+(1===v(a)?"":v(a))+"x");0!==b&&(f+=(0<=b?"+":"-")+(1===v(b)?"":v(b))+"y");0!==c&&(f+=(0<=c?"+":"-")+v(c));return f.slice(1)+"=0"};r.prototype.getNormalVector=function(){return new m(this.a,this.b)};r.prototype.getIntersection=function(a){if(q(this.a*a.b,a.a*this.b))return!1;var b=(a.a*this.c-this.a*a.c)/(this.a*a.b-a.a*this.b);return new n(0===this.a?-1*(a.b*b+a.c)/a.a:-1*(this.b*b+this.c)/this.a,b)};r.prototype.equals=function(a){if(!e.prototype.equals.call(this,
a))return!1;var b=q(this.a*a.b,this.b*a.a),c=q(this.b*a.c,this.c*a.b);a=q(this.a*a.c,this.c*a.a);return b&&c&&a};r.prototype.isParallelTo=function(a){return this.equals(a)?!1:q(this.a*a.b,this.b*a.a)};r.prototype.isPerpendicularTo=function(a){return this.equals(a)?!1:q(this.a*a.a+this.b*a.b,0)};r.prototype.name=function(){return"Line"};r.fromVector=function(a,b){var c=a,f=b;"Point"===a.name()&&(c=a.toVector());"Point"===b.name()&&(f=b.toVector());return new r(c,c.add(f))};r.prototype.toString=r.prototype.inspect=
r.prototype.getEquation;var t=function(a){var b,c=[];for(b=0;b<arguments.length;++b)c[b-0]=arguments[b];b=e.call(this)||this;c=1<=c.length?c:[];Array.isArray(c[0])?b.points=c[0]:b.points=c;return b};$jscomp.inherits(t,e);t.prototype.equals=function(){return!1};t.prototype.move=function(a,b){if(0===a&&0===b)return this;for(var c=[],f=0,d=this.points.length;f<d;f=0|f+1)c[f]=this.points[f].move(a,b);return(new t(c)).setStyle(this.style)};t.prototype.rotate=function(a,b){if(0===a%(2*Math.PI))return this;
for(var c=[],f=0,d=this.points.length;f<d;f=0|f+1)c[f]=this.points[f].rotate(a,b);return(new t(c)).setStyle(this.style)};t.prototype.has=function(a){var b=this.points[this.points.length-1];for(var c=0,f=0,d=this.points.length;f<d;f=0|f+1){var e=this.points[f];var g=(new m(e)).subtract(new m(a));b=(new m(b)).subtract(new m(a));if(0===g.abs()||0===b.abs())return!0;g=g.product(b)/(g.abs()*b.abs());c+=Math.acos(g);b=e}return q(c,0)||q(c,2*Math.PI)};t.prototype.name=function(){return"Polygon"};var u=function(a,
b){var c=e.call(this)||this;c.points=a.x>b.x?[b,a]:[a,b];c.length=Math.sqrt(Math.pow(a.x-b.x,2)+Math.pow(a.y-b.y,2));return c};$jscomp.inherits(u,e);u.prototype.move=function(a,b){return 0===a&&0===b?this:(new u(this.points[0].move(a,b),this.points[1].move(a,b))).setStyle(this.style)};u.prototype.has=function(a){var b=this.points[0],c=this.points[1];return b.x<=a.x&&a.x<=c.x&&(b.y<=c.y&&b.y<=a.y&&a.y<=c.y||b.y>=c.y&&b.y>=a.y&&a.y>=c.y)&&this.toLine().has(a)?!0:!1};u.prototype.intersects=function(a){var b=
a instanceof r?this.toLine().getIntersection(a):this.toLine().getIntersection(a.toLine());return!1===b?!1:this.has(b)&&a.has(b)};u.prototype.toLine=function(){return new r(this.points[0],this.points[1])};u.prototype.equals=function(a){return e.prototype.equals.call(this,a)?this.points[0].equals(a.points[0])&&this.points[1].equals(a.points[1]):!1};u.prototype.name=function(){return"Segment"};var y=function(a,b,c){if(null==a||null==b||null==c)throw Error("Triangle must have three vertices.");if(a.equals(b)||
b.equals(c)||a.equals(c))throw Error("Triangle must have three vertices.");return t.call(this,a,b,c)||this};$jscomp.inherits(y,t);y.prototype.getCircumcircle=function(){var a=this.points[0],b=this.points[1],c=this.points[2],f=new u(a,b),d=new u(b,c),e=new u(c,a),g=this.getArea();a=new m(a.x,a.y);b=new m(b.x,b.y);c=new m(c.x,c.y);var h=Math.pow(d.length,2),l=Math.pow(e.length,2),k=Math.pow(f.length,2);g=(new m(0,0)).add(a.multiple(h*(l+k-h))).add(b.multiple(l*(k+h-l))).add(c.multiple(k*(h+l-k))).multiple(1/
(16*Math.pow(g,2)));g=new n(g.x,g.y);f=b.subtract(a).product(c.subtract(a))/(f.length*e.length);return new w(g,d.length/Math.sqrt(1-Math.pow(f,2))/2)};y.prototype.getIncircle=function(){var a=new m(this.points[0].x,this.points[0].y),b=new m(this.points[1].x,this.points[1].y),c=new m(this.points[2].x,this.points[2].y),f=c.subtract(b).abs(),d=c.subtract(a).abs(),e=b.subtract(a).abs();a=(new m(0,0)).add(a.multiple(f/(f+d+e))).add(b.multiple(d/(f+d+e))).add(c.multiple(e/(f+d+e)));a=new n(a.x,a.y);f=2*
this.getArea()/(f+d+e);return new w(a,f)};y.prototype.getCenter=function(){var a=this.points[0],b=this.points[1],c=this.points[2];return new n((a.x+b.x+c.x)/3,(a.y+b.y+c.y)/3)};y.prototype.getArea=function(){var a=this.points[0],b=this.points[1],c=this.points[2],f=new u(a,b),d=new u(a,c);b=new m(b.x-a.x,b.y-a.y);a=new m(c.x-a.x,c.y-a.y);a=b.product(a)/(f.length*d.length);return f.length*d.length*Math.sqrt(1-Math.pow(a,2))/2};y.prototype.move=function(a,b){if(0===a&&0===b)return this;a=t.prototype.move.call(this,
a,b);return(new y(a.points[0],a.points[1],a.points[2])).setStyle(this.style)};y.prototype.rotate=function(a,b){if(0===a%(2*Math.PI))return this;"undefined"===typeof b&&(b=this.getCenter());a=t.prototype.rotate.call(this,a,b);return(new y(a.points[0],a.points[1],a.points[2])).setStyle(this.style)};y.prototype.name=function(){return"Triangle"};var H=function(a,b,c,f){if(a.equals(b)||a.equals(c)||a.equals(f)||b.equals(c)||b.equals(f)||c.equals(f))throw Error("ABCD is not a quadrilateral.");if((new u(a,
f)).intersects(new u(b,c))||(new u(a,b)).intersects(new u(c,f)))throw Error("ABCD is not a quadrilateral.");return t.call(this,a,b,c,f)||this};$jscomp.inherits(H,t);H.prototype.getArea=function(){var a=this.points[0],b=this.points[2],c=this.points[3],f=(new y(a,this.points[1],b)).getArea();a=(new y(a,b,c)).getArea();return f+a};H.prototype.move=function(a,b){if(0===a&&0===b)return this;a=t.prototype.move.call(this,a,b);return(new H(a.points[0],a.points[1],a.points[2],a.points[3])).setStyle(this.style)};
H.prototype.rotate=function(a,b){if(0===a%(2*Math.PI))return this;a=t.prototype.rotate.call(this,a,b);return(new H(a.points[0],a.points[1],a.points[2],a.points[3])).setStyle(this.style)};H.prototype.name=function(){return"Quadrilateral"};var I=function(a,b){return t.call(this,a,b)||this};$jscomp.inherits(I,t);I.prototype.has=function(a){var b=this.points[0],c=this.points[1];return 0>=(b.x-a.x)*(c.x-a.x)&&0>=(b.y-a.y)*(c.y-a.y)};I.prototype.move=function(a,b){if(0===a&&0===b)return this;a=t.prototype.move.call(this,
a,b);return(new I(a.points[0],a.points[1])).setStyle(this.style)};I.prototype.rotate=function(a,b){if(0===a%(2*Math.PI))return this;a=t.prototype.rotate.call(this,a,b);return(new I(a.points[0],a.points[1])).setStyle(this.style)};I.prototype.name=function(){return"Rect"};var E=function(a,b,c,f){c=void 0===c?"left":c;f=void 0===f?null:f;var d=g.call(this)||this;d.P=b;d.string=a;d.text=a;d.strokesOutline=!1;d.style.align=c;d.style.maxWidth=f;d.style.fillStyle="#000";d.style.outlineColor="#000";d.style.baseline=
"alphabetic";d.style.font=null;return d};$jscomp.inherits(E,g);E.prototype.strokeOutline=function(){this.strokesOutline=!0;return this};E.prototype.setAlign=function(a){this.style.align=a;return this};E.prototype.setOutlineColor=function(a){this.style.outlineColor=a;return this};E.prototype.setBaseline=function(a){this.style.baseline=a;return this};E.prototype.setFont=function(a){this.style.font=a;return this};E.prototype.move=function(a,b){if(0===a&&0===b)return this;a=(new E(this.string,this.P.move(a,
b),this.style.align,this.style.maxWidth)).setStyle(this.style);this.strokesOutline&&a.strokeOutline();return a};E.prototype.name=function(){return"Text"};var x={distance:function(a,b){if(a instanceof n&&b instanceof n)return Math.sqrt((a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y));if(a instanceof n&&b instanceof r)return a=b.a*a.x+b.b*a.y+b.c,0>a&&(a*=-1),a/=Math.sqrt(b.a*b.a+b.b*b.b);if(a instanceof r&&b instanceof n)return distance(b,a)},UnitaryObject:g,ContouredObject:e,BaseVector:k,BezierCurve:l,Circle:w,
CircularSector:z,Curve:F,Doughnut:C,Donut:C,Ellipse:A,Graph:J,Group:G,Image:D,Line:r,Point:n,Polygon:t,Quadrilateral:H,Rect:I,Segment:u,Text:E,Triangle:y,Vector3D:B,Vector:m,XAxis:new r(new n(0,0),new n(1,0)),YAxis:new r(new n(0,0),new n(0,1)),VERSION:"0.1.2"},L=[],M=function(a){console.log(a)},p=function(a,b,c){var f=this;b=void 0===b?300:b;c=void 0===c?300:c;this.ready=Promise.resolve();"complete"!==document.readyState&&(this.ready=new Promise(function(a){return document.addEventListener("DOMContentLoaded",
a)}));this.ready.then(function(){if(null===document.getElementById(a)){var d=document.createElement("canvas");d.setAttribute("id",a);d.width=b;d.height=c;f.element=d}else f.element=document.getElementById(a);f.canvas=f.element.getContext("2d");f.canvasWidth=f.element.width;f.canvasHeight=f.element.height});this.id=a;this.objects=[];this.mode="graph";this.origin=new x.Point(0,0);for(var d="click mousedown mouseup touchstart touchend keypress keydown keyup".split(" "),e=0,g=d.length;e<g;e++)this.listen(d[e])};
p.prototype.listen=function(a){var b=this;this.ready.then(function(){return b.element.addEventListener(a,d.bind(b),!1)})};p.prototype.add=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];[].push.apply(this.objects,b)};p.prototype.removeAllObjects=function(){this.objects=[]};p.prototype.clear=function(){var a=this;this.ready.then(function(){return a.canvas.clearRect(0,0,a.canvasWidth,a.canvasHeight)})};p.prototype.X=function(a){return Math.round(a+this.origin.x)};p.prototype.Y=
function(a){return"normal"===this.mode?Math.round(a+this.origin.y):Math.round(this.canvasHeight-(a+this.origin.y))};p.prototype.draw=function(){var a=this,b=[],c=function(a,c){b[b.length]=(new Promise(function(b,d){if(L[a])var f=L[a];else f=new Image,f.src=a,L[a]=f;f.loaded?(c.__image__=f,b()):(f.addEventListener("load",function(){c.__image__=f;f.loaded=!0;b()}),f.addEventListener("error",d))})).catch(M)},d=function(a){for(var b=0,f=a.length;b<f;b=0|b+1){var e=a[b];"Image"===e.name()?e.__image__||
c(e.src,e):"Group"===e.name()&&d(e.group)}};d(this.objects);return Promise.all(b.concat(this.ready)).then(function(){for(var b=0,c=a.objects.length;b<c;b=0|b+1)a.__drawHelper__(a.objects[b])}).catch(M)};p.prototype.__drawHelper__=function(a){var b=a.name();this.canvas.fillStyle="#000";this.canvas.strokeStyle="#000";a.style&&null!==a.style.fillStyle&&(this.canvas.fillStyle=a.style.fillStyle);a.style&&null!==a.style.strokeStyle&&(this.canvas.strokeStyle=a.style.strokeStyle);this.canvas.setLineDash&&
(a.getLineDash&&null!==a.getLineDash()?this.canvas.setLineDash(a.getLineDash()):this.canvas.setLineDash([]));a.getLineCap&&null!==a.getLineCap()?this.canvas.lineCap=a.getLineCap():this.canvas.lineCap="butt";a.getLineDashOffset&&null!==a.getLineDashOffset()?this.canvas.lineDashOffset=a.getLineDashOffset():this.canvas.lineDashOffset=0;a.getLineJoin&&null!==a.getLineJoin()?this.canvas.lineJoin=a.getLineJoin():this.canvas.lineJoin="miter";a.getLineWidth&&null!==a.getLineWidth()?this.canvas.lineWidth=
a.getLineWidth():this.canvas.lineWidth=1;p.painter[b].call(this,a)};p.prototype.toDataURL=function(){return this.element.toDataURL()};p.preload=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];c=[];for(var f={},d=0,e=b.length;d<e;f={src:f.src},d=0|d+1)f.src=b[d],L[f.src]||(c[c.length]=(new Promise(function(a){return function(b,c){var d=new Image;d.src=a.src;d.addEventListener("load",function(){d.loaded=!0;b()});d.addEventListener("error",c);L[a.src]=d}}(f))).catch(M));return Promise.all(c).catch(M)};
x.UnitaryObject.prototype.on=function(a,b){this.handlers||(this.handlers={});this.handlers[a]||(this.handlers[a]=[]);this.handlers[a].push(b);return this};x.UnitaryObject.prototype.trigger=function(a,b){if(!this.handlers||!this.handlers[a])return this;for(var c=0,d=this.handlers[a].length;c<d;c=0|c+1)this.handlers[a][c](b);return this};p.painter={};p.painter.BezierCurve=function(a){var b=this;this.canvas.beginPath();var c=a.controlPoints,d=c,e=[],g=a.points||[c[0]],h=1,l=a.step;if(!(1>=c.length)){if(2<=
c.length&&4>=c.length)g=c.map(function(a){return{x:b.X(a.x),y:b.Y(a.y)}}),this.canvas.moveTo(g[0].x,g[0].y),2===g.length?this.canvas.lineTo(g[1].x,g[1].y):3===g.length?this.canvas.quadraticCurveTo(g[1].x,g[1].y,g[2].x,g[2].y):4===g.length&&this.canvas.bezierCurveTo(g[1].x,g[1].y,g[2].x,g[2].y,g[3].x,g[3].y);else{if(!a.points){for(var k=0;1>k;k+=l){d=c.concat();for(var m=0,n=c.length-1;m<n;m=0|m+1){for(var p=0,q=d.length-1;p<q;p=0|p+1)e[p]=new x.Point(d[p+1].x*k+d[p].x*(1-k),d[p+1].y*k+d[p].y*(1-k));
d=e;e=[]}g[h]=d[0];h=0|h+1}g[h]=c[c.length-1]}a.points=g;this.canvas.moveTo(this.X(g[0].x),this.Y(g[0].y));a=0;for(n=g.length;a<n;a=0|a+1)this.canvas.lineTo(this.X(g[a].x),this.Y(g[a].y))}this.canvas.stroke()}};p.painter.Circle=function(a){var b=a.center,c=a.r;this.canvas.beginPath();this.canvas.arc(this.X(b.x),this.Y(b.y),c,0,2*Math.PI,a.anticlockwise);null!==a.style.fillStyle&&this.canvas.fill();this.canvas.stroke()};p.painter.CircularSector=function(a){var b=a.center,c=a.r,d=a.startAngle,e=a.endAngle;
this.canvas.beginPath();this.canvas.moveTo(this.X(b.x),this.Y(b.y));this.canvas.arc(this.X(b.x),this.Y(b.y),c,d,e,a.anticlockwise);this.canvas.closePath();null!==a.style.fillStyle&&this.canvas.fill();this.canvas.stroke()};p.painter.Curve=function(a){this.canvas.beginPath();for(var b=a.start,c=a.end,d=a.x,e=a.y,g=[],h=1/(c-b);b<=c;b+=h){var k=(new x.Vector((d(b+h)-d(b))*a.scale,(e(b+h)-e(b))*a.scale)).theta/(2*Math.PI)*360;Number.isNaN(d(b))||Number.isNaN(e(b))||(g[g.length]=new x.Point(d(b)*a.scale,
e(b)*a.scale));if(45<=k&&135>=k||225<=k&&315>=k)Number.isNaN(d(b+h/2))||Number.isNaN(e(b+h/2))||(g[g.length]=new x.Point(d(b+h/2)*a.scale,e(b+h/2)*a.scale))}this.canvas.moveTo(this.X(g[0].x),this.Y(g[0].y));a=0;for(c=g.length;a<c;a=0|a+1)this.canvas.lineTo(this.X(g[a].x),this.Y(g[a].y));this.canvas.stroke()};p.painter.Doughnut=function(a){var b=a.center,c=this.X(b.x);b=this.Y(b.y);var d=a.innerRadius,e=a.outerRadius;null!==a.style.fillStyle&&(this.canvas.beginPath(),this.canvas.arc(c,b,e,0,2*Math.PI,
!1),this.canvas.arc(c,b,d,0,2*Math.PI,!0),this.canvas.fill());this.canvas.beginPath();this.canvas.arc(c,b,e,0,2*Math.PI,!1);this.canvas.stroke();this.canvas.beginPath();this.canvas.arc(c,b,d,0,2*Math.PI,!0);this.canvas.stroke()};p.painter.Ellipse=function(a){var b=a.center;this.canvas.beginPath();this.canvas.ellipse?(this.canvas.ellipse(this.X(b.x),this.Y(b.y),a.a,a.b,a.angle,0,2*Math.PI,a.anticlockwise),null!==a.style.fillStyle&&this.canvas.fill(),this.canvas.stroke()):(this.canvas.save(),this.canvas.setTransform(1,
0,0,1,0,0),this.canvas.translate(this.X(b.x),this.Y(b.y)),this.canvas.rotate(a.angle),this.canvas.scale(1,a.b),this.canvas.arc(this.X(b.x),this.Y(b.y),a.a,0,2*Math.PI,a.anticlockwise),null!==a.style.fillStyle&&this.canvas.fill(),this.canvas.stroke(),this.canvas.restore())};p.painter.Graph=function(a){this.canvas.beginPath();var b=a.start,c=a.end;null===b&&(b=-this.origin.x);null===c&&(c=this.canvasWidth-this.origin.x);for(var d=[];b<=c;b=0|b+1){var e=(new x.Vector(1,(a.f((b+1)/a.scale)-a.f(b/a.scale))*
a.scale)).theta/(2*Math.PI)*360;Number.isNaN(a.f(b/a.scale))||(d[d.length]=new x.Point(b,a.f(b/a.scale)*a.scale));if(45<=e&&135>=e||225<=e&&315>=e)Number.isNaN(a.f((b+.5)/a.scale))||(d[d.length]=new x.Point(b+.5,a.f((b+.5)/a.scale)*a.scale))}this.canvas.moveTo(this.X(d[0].x),this.Y(d[0].y));a=0;for(c=d.length;a<c;a=0|a+1)this.canvas.lineTo(this.X(d[a].x),this.Y(d[a].y));this.canvas.stroke()};p.painter.Group=function(a){var b={},c=["Cap","Dash","DashOffset","Join","Width"];b.fillStyle=a.style.fillStyle;
b.strokeStyle=a.style.strokeStyle;for(var d=0,e=c.length;d<e;d++){var g=c[d];a["getLine"+g]&&null!==a["getLine"+g]()&&(b[g]=a[g]())}d=0;for(e=a.group.length;d<e;d=0|d+1){g=a.group[d];var h=[],k={fillStyle:h,strokeStyle:h};g.style&&null!==g.style.fillStyle||(k.fillStyle=g.style.fillStyle,g.style.fillStyle=b.fillStyle);g.style&&null!==g.style.strokeStyle||(k.strokeStyle=g.style.strokeStyle,g.style.strokeStyle=b.strokeStyle);this.__drawHelper__(g);k.fillStyle!==h&&(g.style.fillStyle=k.fillStyle);k.strokeStyle!==
h&&(g.style.fillStyle=k.fillStyle);var l=0;for(e=c.length;l<e;l++){var m=c[l];if(k[m]!==h)g["setLine"+m](k[m])}}};p.painter.Image=function(a){var b=a.__image__;null!==a.dx&&null!==a.sx?this.canvas.drawImage(b,a.sx,a.sy,a.sw,a.sh,this.X(a.dx),this.Y(a.dy),a.dw,a.dh):null!==a.dx&&null===a.sx&&null!==a.dw?this.canvas.drawImage(b,this.X(a.dx),this.Y(a.dy),a.dw,a.dh):null!==a.dx&&null===a.dw?this.canvas.drawImage(b,this.X(a.dx),this.Y(a.dy)):null===a.dx&&this.canvas.drawImage(b)};p.painter.Line=function(a){var b=
x.Segment,c=x.Point,d=this.canvasWidth,e=this.canvasHeight,g=(new b(new c(0,0),new c(0,e))).move(-this.origin.x,-this.origin.y),h=(new b(new c(d,0),new c(d,e))).move(-this.origin.x,-this.origin.y),k=(new b(new c(0,0),new c(d,0))).move(-this.origin.x,-this.origin.y);d=(new b(new c(0,e),new c(d,e))).move(-this.origin.x,-this.origin.y);c=b=null;g.intersects(a)&&(b=g.toLine().getIntersection(a));h.intersects(a)&&(c=h.toLine().getIntersection(a));k.intersects(a)&&d.intersects(a)?(g=k.toLine().getIntersection(a),
a=d.toLine().getIntersection(a),g.x>a.x?(b=g,c=a):(b=a,c=g)):k.intersects(a)&&!d.intersects(a)?(a=k.toLine().getIntersection(a),null==b?b=a:c=a):!k.intersects(a)&&d.intersects(a)&&(a=d.toLine().getIntersection(a),null==c?c=a:b=a);null!=b&&null!=c&&(this.canvas.beginPath(),this.canvas.moveTo(this.X(b.x),this.Y(b.y)),this.canvas.lineTo(this.X(c.x),this.Y(c.y)),this.canvas.stroke())};p.painter.Point=function(a){this.canvas.fillRect(this.X(a.x),this.Y(a.y),1,1)};p.painter.Rect=function(a){var b=this.X(a.points[0].x),
c=this.Y(a.points[0].y),d=a.points[1].x-a.points[0].x,e=a.points[1].y-a.points[0].y;"normal"!==this.mode&&(e=-(a.points[1].y-a.points[0].y));null!==a.style.fillStyle?this.canvas.fillRect(b,c,d,e):this.canvas.strokeRect(b,c,d,e)};p.painter.Segment=function(a){this.canvas.beginPath();this.canvas.moveTo(this.X(a.points[0].x),this.Y(a.points[0].y));this.canvas.lineTo(this.X(a.points[1].x),this.Y(a.points[1].y));this.canvas.stroke()};p.painter.Text=function(a){this.canvas.textAlign=a.style.align;this.canvas.textBaseline=
a.style.baseline;var b=this.X(a.P.x),c=this.Y(a.P.y),d=a.style.maxWidth;if(null!==a.style.font){var e=this.canvas.font;this.canvas.font=a.style.font}null===d?(a.style.strokesOutline&&this.canvas.strokeText(a.text,b,c),this.canvas.fillText(a.text,b,c)):(a.style.strokesOutline&&this.canvas.strokeText(a.text,b,c,d),this.canvas.fillText(a.text,b,c,d));null!==a.style.font&&(this.canvas.font=e)};p.painter.Polygon=h;p.painter.Quadrilateral=h;p.painter.Triangle=h;return Object.assign({},x,{Canvas:p})});